//Paul Lyon
//8-3.cpp

#include <iostream.h>

int main()
{
	cout << "The size of an int is: \t\t" << sizeof(int) << " bytes";
	cout << "The size of an short is: \t\t" << sizeof(short) << " bytes";
	cout << "The size of an long is: \t\t" << sizeof(long) << " bytes";
	cout << "The size of an char is: \t\t" << sizeof(char) << " bytes";
	cout << "The size of an float is: \t\t" << sizeof(float) << " bytes";
	cout << "The size of an double is: \t\t" << sizeof(double) << " bytes";
	cout << "The size of an bool is: \t\t" << sizeof(bool) << " bytes";
	return 0;
}